token: "*** your token ***"

messages:
  welcome:
    start: "Привет! Это главный GirlFriendAI бот, который создает AI девушек для общения с ними."
  create:
    start: "Начнем создание твоей идеальной AI девушки."
    name: "Введите имя девушки"
    age: "Введите возраст девушки"
    face: "Отправьте фото предпочитаемого лица девушки"
    features: "Опишите ее внешность, например 'голубые глаза, узкая талия' и т.д."
  edit:
    start: "Выберите девушку, которую хотите изменить"

buttons:
  welcome:
    create: "🍓 Создать AI девушку"
    edit: "🍒 Изменить AI девушку"
    remove: "🍎 Удалить AI девушку"
  create:
    name: "Имя"
    age: "Возраст"
    face: "Лицо"
    features: "Внешность"
    preview: "Превью"
    save: "Сохранить"
