callback_messages:
  add:
    name: "Имя успешно сохранено!"
    age: "Возраст успешно сохранен!"
    appearance: "Описание внешности успешно сохранено!"
    face: "Фото лица успешно сохранено!"
    username: "Ник успешно сохранен!"
    interests: "Интересы девушки успешно сохранены!"
  preview: "Вот, что уже есть:\n*Имя*: {name}\n*Возраст*: {age}\n*Внешность*: {appearance}"
  save: "Поздравляем! Ваша AI девушка создана! В скором времени она Вам напишет."

messages:
  welcome: "Привет! Это главный GirlFriendAI бот, который создает AI девушек для общения с ними."
  create: "Создадим твою идеальную девушку!"
  add:
    name: "Как будут звать Вашу будущую AI девушку?\nВведите имя, например `Катя`."
    age: "Сколько лет Вашей AI девушке?\nВведите возраст, например `20`."
    appearance: "Опишите Вашу девушку, например `спортивная фигура, голубые глаза`."
    face: "Какое личико у вашей девушки? Отправьте фото лица."
    username: "Отправьте желаемый ник для девушки.\n*Важно*: ник должен заканчиваться на `bot`, 
              например `SweetGirlBot` или `sweet_girl_bot`."
    interests: "Чем интересуется Ваша девушка?\nВведите текст, например `лыжный спорт, чтение книг`"


limitations:
  name_len:
    min: 3
    max: 10
  appearance_len:
    min: 1
    max: 100
  age:
    min: 18
    max: 60
  username_len:
    min: 5
    max: 32
  interests_len:
    min: 1
    max: 100
